import { useEffect, useMemo, useState } from 'react';
import AdminSidebar from '../components/AdminSidebar';
import api from '../core/api/client';
import { isDeveloper } from '../core/auth/permissions';
import toast from 'react-hot-toast';

type Branch={id:number;code:string;name:string;status:string};
type Company={id:number;code:string;name:string;status:string;branches:Branch[]};
type License={plan_code:string;plan_name:string;features:string[];max_users:number|null;max_branches:number|null;starts_at?:string|null;expires_at?:string|null;status?:string;auto_renew?:boolean;notes?:string|null};
type Tenant={id:number;code:string;name:string;status:string;timezone?:string;currency?:string;company_count:number;branch_count:number;license?:License|null;companies:Company[]};
type Admin={membership_id:number;user_id:number;name:string;email:string;status:string;is_primary:boolean;company_id:number;company_name:string;branch_id:number;branch_name:string;role:string;permissions:string[]};
type Permission={id:number;module:string;resource:string;action:string;name:string;description?:string};
type Plan={code:string;name:string;features:string[];max_users:number|null;max_branches:number|null};

const featureLabels:Record<string,string>={pos:'POS',inventory:'Inventory',purchasing:'Purchasing',sales:'Sales',accounting:'Accounting',hrm:'HRM',administration:'Administration',audit:'Audit',organization:'Organization'};
const err=(e:unknown)=>e&&typeof e==='object'&&'response' in e?String((e as {response?:{data?:{message?:string}}}).response?.data?.message??''):'';
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-1 block text-xs font-bold text-stone-500">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-stone-200 px-3 py-2.5 text-sm"/></label>}
function Select({label,value,onChange,disabled=false,children}:{label:string;value:string;onChange:(v:string)=>void;disabled?:boolean;children:React.ReactNode}){return <label className="block"><span className="mb-1 block text-xs font-bold text-stone-500">{label}</span><select value={value} disabled={disabled} onChange={e=>onChange(e.target.value)} className="w-full rounded-xl border border-stone-200 bg-white px-3 py-2.5 text-sm disabled:bg-stone-100"><option value="">Pilih {label.toLowerCase()}...</option>{children}</select></label>}
function Card({title,children,description}:{title:string;children:React.ReactNode;description?:string}){return <section className="rounded-3xl border border-stone-200 bg-white p-5 shadow-sm"><h2 className="font-black text-stone-900">{title}</h2>{description&&<p className="mt-1 text-sm text-stone-500">{description}</p>}<div className="mt-4">{children}</div></section>}

export default function DeveloperConsole(){
 const developer=isDeveloper();
 const [tenants,setTenants]=useState<Tenant[]>([]),[plans,setPlans]=useState<Plan[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[admins,setAdmins]=useState<Admin[]>([]);
 const [tenantId,setTenantId]=useState(''),[companyId,setCompanyId]=useState(''),[branchId,setBranchId]=useState('');
 const [editingAdmin,setEditingAdmin]=useState<Admin|null>(null);
 const [adminForm,setAdminForm]=useState({name:'',email:'',status:'active',company_id:'',branch_id:'',permissions:[] as string[]});
 const [create,setCreate]=useState({name:'',email:'',password:''});
 const [license,setLicense]=useState({plan_code:'',features:[] as string[],expires_at:'',max_users:'',max_branches:'',auto_renew:false,notes:''});
 const tenant=tenants.find(t=>String(t.id)===tenantId),companies=tenant?.companies??[],company=companies.find(c=>String(c.id)===companyId),branches=company?.branches??[];
 const licensedPermissions=useMemo(()=>{const fs=new Set(license.features);return permissions.filter(p=>{const root=p.name.split('.')[0];const f=root==='hr'?'hrm':root==='users'||root==='rbac'?'administration':root;return fs.has(f)})},[license.features,permissions]);
 const load=async()=>{try{const [t,p,pm]=await Promise.all([api.get('/v1/developer/tenants'),api.get('/v1/developer/license-catalog'),api.get('/v1/developer/permissions')]);setTenants(t.data?.data??[]);setPlans(p.data?.data??[]);setPermissions(pm.data?.data??[])}catch(e){toast.error(err(e)||'Data Developer Console gagal dimuat.')}};
 const loadAdmins=async(id:string)=>{if(!id)return setAdmins([]);try{const r=await api.get(`/v1/developer/tenants/${id}/admins`);setAdmins(r.data?.data??[])}catch(e){toast.error(err(e)||'Tenant admin gagal dimuat.')}};
 useEffect(()=>{if(developer)void load()},[developer]);
 useEffect(()=>{void loadAdmins(tenantId);const l=tenants.find(t=>String(t.id)===tenantId)?.license;setLicense({plan_code:l?.plan_code??'',features:l?.features??[],expires_at:l?.expires_at?l.expires_at.slice(0,10):'',max_users:l?.max_users!=null?String(l.max_users):'',max_branches:l?.max_branches!=null?String(l.max_branches):'',auto_renew:Boolean(l?.auto_renew),notes:l?.notes??''});setCompanyId('');setBranchId('')},[tenantId]);
 if(!developer)return <main className="min-h-screen bg-stone-50 p-10"><div className="mx-auto max-w-xl rounded-2xl border border-red-200 bg-white p-8 text-center"><div className="text-4xl">403</div><h1 className="mt-3 font-black">Developer Console</h1></div></main>;
 const chooseTenant=(v:string)=>{setTenantId(v);setCompanyId('');setBranchId('')};
 const saveLicense=async()=>{try{await api.put(`/v1/developer/tenants/${tenantId}/license`,{plan_code:license.plan_code,features:license.features,expires_at:license.expires_at||null,max_users:license.max_users?Number(license.max_users):null,max_branches:license.max_branches?Number(license.max_branches):null,auto_renew:license.auto_renew,notes:license.notes||null});toast.success('Lisensi disimpan');await load()}catch(e){toast.error(err(e)||'Lisensi gagal disimpan')}};
 const createAdmin=async()=>{if(!tenantId||!companyId||!branchId)return toast.error('Tenant, company, dan branch wajib dipilih');try{await api.post('/v1/organizations/tenant-admins',{tenant_id:Number(tenantId),company_id:Number(companyId),branch_id:Number(branchId),...create});toast.success('Tenant admin dibuat');setCreate({name:'',email:'',password:''});await loadAdmins(tenantId)}catch(e){toast.error(err(e)||'Tenant admin gagal dibuat')}};
 const openAdmin=(a:Admin)=>{setEditingAdmin(a);setAdminForm({name:a.name,email:a.email,status:a.status,company_id:String(a.company_id),branch_id:String(a.branch_id),permissions:a.permissions})};
 const saveAdmin=async()=>{if(!editingAdmin)return;try{await api.put(`/v1/developer/tenant-admins/${editingAdmin.membership_id}`,{...adminForm,company_id:Number(adminForm.company_id),branch_id:Number(adminForm.branch_id)});toast.success('Tenant admin diperbarui');await loadAdmins(tenantId);setEditingAdmin(null)}catch(e){toast.error(err(e)||'Gagal memperbarui tenant admin')}};
 return <div className="flex min-h-screen bg-stone-50 text-stone-800"><AdminSidebar activePage="developer-console"/><main className="min-w-0 flex-1 overflow-auto p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6">
  <header><div className="text-xs font-black uppercase tracking-[.18em] text-amber-700">Platform · God Mode</div><h1 className="mt-1 text-3xl font-black">Developer Console</h1><p className="mt-1 text-sm text-stone-500">Kontrol tenant, struktur organisasi, lisensi, akun tenant-admin, dan entitlement permission.</p></header>
  <div className="grid gap-4 md:grid-cols-4">{[['Tenant',tenants.length,'🏢'],['Company',tenants.reduce((n,t)=>n+t.company_count,0),'🏷️'],['Branch',tenants.reduce((n,t)=>n+t.branch_count,0),'📍'],['Authority','GOD MODE','⚡']].map(([a,b,c])=><div key={String(a)} className="rounded-2xl bg-stone-900 p-5 text-white"><div>{c}</div><div className="mt-2 text-xs text-stone-400">{a}</div><div className="font-black">{b}</div></div>)}</div>
  <Card title="Tenant & Lisensi" description="Lisensi adalah sumber entitlement fitur. Permission tenant-admin tidak boleh keluar dari fitur yang berlisensi."><div className="grid gap-4 lg:grid-cols-3"><Select label="Tenant" value={tenantId} onChange={chooseTenant}>{tenants.map(t=><option key={t.id} value={t.id}>{t.id} · {t.code} · {t.name}</option>)}</Select><Select label="Plan" value={license.plan_code} disabled={!tenantId} onChange={v=>{const p=plans.find(x=>x.code===v);setLicense(f=>({...f,plan_code:v,features:p?.features??f.features}))}}>{plans.map(p=><option key={p.code} value={p.code}>{p.name}</option>)}</Select><Field label="Expired" type="date" value={license.expires_at} onChange={v=>setLicense(f=>({...f,expires_at:v}))}/></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{Object.entries(featureLabels).map(([k,v])=><label key={k} className="flex items-center gap-2 rounded-xl border border-stone-200 px-3 py-2.5 text-sm"><input type="checkbox" checked={license.features.includes(k)} onChange={e=>setLicense(f=>({...f,features:e.target.checked?[...f.features,k]:f.features.filter(x=>x!==k)}))}/>{v}</label>)}</div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Field label="Max User" type="number" value={license.max_users} onChange={v=>setLicense(f=>({...f,max_users:v}))}/><Field label="Max Branch" type="number" value={license.max_branches} onChange={v=>setLicense(f=>({...f,max_branches:v}))}/><label className="flex items-center gap-2 rounded-xl border border-stone-200 px-3"><input type="checkbox" checked={license.auto_renew} onChange={e=>setLicense(f=>({...f,auto_renew:e.target.checked}))}/>Auto renewal</label></div><button onClick={saveLicense} className="mt-4 rounded-xl bg-stone-900 px-4 py-2.5 text-sm font-bold text-white">Simpan Lisensi</button></Card>
  <Card title="Pembuatan Tenant Admin" description="Dropdown berantai: Tenant → Company → Branch."><div className="grid gap-4 lg:grid-cols-3"><Select label="Tenant ID" value={tenantId} onChange={chooseTenant}>{tenants.map(t=><option key={t.id} value={t.id}>{t.id} · {t.name}</option>)}</Select><Select label="Company ID" value={companyId} disabled={!tenantId} onChange={setCompanyId}>{companies.map(c=><option key={c.id} value={c.id}>{c.id} · {c.name}</option>)}</Select><Select label="Branch ID" value={branchId} disabled={!companyId} onChange={setBranchId}>{branches.map(b=><option key={b.id} value={b.id}>{b.id} · {b.name}</option>)}</Select></div><div className="mt-4 grid gap-4 lg:grid-cols-3"><Field label="Nama" value={create.name} onChange={v=>setCreate(f=>({...f,name:v}))}/><Field label="Email" value={create.email} onChange={v=>setCreate(f=>({...f,email:v}))}/><Field label="Password" type="password" value={create.password} onChange={v=>setCreate(f=>({...f,password:v}))}/></div><button onClick={createAdmin} className="mt-4 rounded-xl bg-amber-700 px-4 py-2.5 text-sm font-bold text-white">Buat Tenant Admin</button></Card>
  <Card title="Tenant / Company / Branch" description="Satu tabel hierarchy untuk provisioning dan pengawasan lisensi."><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead><tr className="border-b border-stone-200 text-left text-xs uppercase text-stone-500"><th className="px-3 py-3">Tenant</th><th>Plan</th><th>Status</th><th>Company</th><th>Branch</th><th>Limit</th></tr></thead><tbody>{tenants.flatMap(t=>t.companies.flatMap(c=>c.branches.map(b=><tr key={`${t.id}-${c.id}-${b.id}`} className="border-b border-stone-100"><td className="px-3 py-3"><b>{t.id} · {t.name}</b><div className="text-xs text-stone-400">{t.code}</div></td><td>{t.license?.plan_name??'Unlicensed'}</td><td>{t.status}</td><td>{c.id} · {c.name}</td><td>{b.id} · {b.name}</td><td>{t.license?.max_users??'∞'} users · {t.license?.max_branches??'∞'} branches</td></tr>)))}</tbody></table></div></Card>
  <Card title="Tenant Admin & Permission" description="Edit akun dan pilih hanya permission yang diperbolehkan oleh lisensi aktif.">{!tenantId?<p className="text-sm text-stone-500">Pilih tenant.</p>:admins.length===0?<p className="text-sm text-stone-500">Belum ada tenant-admin.</p>:<div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="border-b border-stone-200 text-left text-xs uppercase text-stone-500"><th className="px-3 py-3">Akun</th><th>Company</th><th>Branch</th><th>Status</th><th>Permissions</th><th></th></tr></thead><tbody>{admins.map(a=><tr key={a.membership_id} className="border-b border-stone-100"><td className="px-3 py-3"><b>{a.name}</b><div className="text-xs text-stone-400">{a.email}</div></td><td>{a.company_name}</td><td>{a.branch_name}</td><td>{a.status}</td><td>{a.permissions.length}</td><td><button onClick={()=>openAdmin(a)} className="rounded-lg border border-stone-200 px-3 py-1.5 text-xs font-bold">Edit</button></td></tr>)}</tbody></table></div>}</Card>
  {editingAdmin&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="max-h-[90vh] w-full max-w-5xl overflow-auto rounded-3xl bg-white p-6"><div className="flex items-center justify-between"><div><div className="text-xs font-black uppercase text-amber-700">Edit Tenant Admin</div><h2 className="text-2xl font-black">{editingAdmin.name}</h2></div><button onClick={()=>setEditingAdmin(null)} className="rounded-xl border px-3 py-2">×</button></div><div className="mt-5 grid gap-4 lg:grid-cols-3"><Field label="Nama" value={adminForm.name} onChange={v=>setAdminForm(f=>({...f,name:v}))}/><Field label="Email" value={adminForm.email} onChange={v=>setAdminForm(f=>({...f,email:v}))}/><Select label="Status" value={adminForm.status} onChange={v=>setAdminForm(f=>({...f,status:v}))}><option value="active">Active</option><option value="inactive">Inactive</option></Select><Select label="Company" value={adminForm.company_id} onChange={v=>setAdminForm(f=>({...f,company_id:v,branch_id:''}))}>{companies.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</Select><Select label="Branch" value={adminForm.branch_id} onChange={v=>setAdminForm(f=>({...f,branch_id:v}))}>{(companies.find(c=>String(c.id)===adminForm.company_id)?.branches??[]).map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</Select></div><div className="mt-5"><div className="mb-2 text-sm font-black">Licensed Permissions · {licensedPermissions.length}</div><div className="grid max-h-80 gap-2 overflow-auto rounded-2xl border p-3 md:grid-cols-2">{licensedPermissions.map(p=><label key={p.name} className="flex gap-2 rounded-xl border border-stone-100 px-3 py-2 text-xs"><input type="checkbox" checked={adminForm.permissions.includes(p.name)} onChange={e=>setAdminForm(f=>({...f,permissions:e.target.checked?[...f.permissions,p.name]:f.permissions.filter(x=>x!==p.name)}))}/><span><b>{p.name}</b>{p.description&&<span className="block text-stone-400">{p.description}</span>}</span></label>)}</div></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEditingAdmin(null)} className="rounded-xl border px-4 py-2.5 text-sm font-bold">Batal</button><button onClick={saveAdmin} className="rounded-xl bg-stone-900 px-4 py-2.5 text-sm font-bold text-white">Simpan</button></div></div></div>}
 </div></main></div>;
}
