import { useEffect, useState } from 'react';
import api from '../../core/api/client';
import PermissionGate from '../../components/PermissionGate';
import EnterpriseAdminLayout from '../../layouts/EnterpriseAdminLayout';
import toast from 'react-hot-toast';

type Role = { id:number; name:string; code:string; permissions?: {name:string}[] };
type Permission = { id:number; module:string; resource:string; action:string; name:string };
type Audit = { id:number; event:string; module:string; entity_type?:string; entity_id?:string; created_at:string };
type Warehouse = { id:number; code:string; name:string };
type Location = { id:number; code:string; name:string; type:'store'|'warehouse'|'office'; status:string; address?:string; latitude?:string|number|null; longitude?:string|number|null };
type Branch = { id:number; code:string; name:string; type?:string; warehouses?: Warehouse[]; locations?: Location[] };
type Company = { id:number; code:string; name:string; legal_name?:string; email?:string; phone?:string; branches?:Branch[] };

export default function FoundationAdmin(){
  const [roles,setRoles]=useState<Role[]>([]); const [permissions,setPermissions]=useState<Permission[]>([]); const [audits,setAudits]=useState<Audit[]>([]); const [companies,setCompanies]=useState<Company[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false);
  const [companyForm,setCompanyForm]=useState({code:'',name:'',legal_name:'',email:'',phone:'',address:''});
  const [branchForm,setBranchForm]=useState({company_id:'',code:'',name:'',type:'store',email:'',phone:'',address:''});
  const [locationForm,setLocationForm]=useState({branch_id:'',code:'',name:'',type:'store',email:'',phone:'',address:'',latitude:'',longitude:''});
  const [editingLocation,setEditingLocation]=useState<number|null>(null);

  const loadOrganizations=async()=>{const response=await api.get('/v1/organizations');setCompanies(response.data?.data||[]);};
  useEffect(()=>{Promise.all([api.get('/v1/roles'),api.get('/v1/permissions'),api.get('/v1/audit-logs?per_page=10'),loadOrganizations()]).finally(()=>setLoading(false));},[]);
  const saveCompany=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{await api.post('/v1/organizations/companies',companyForm);toast.success('Company berhasil ditambahkan.');setCompanyForm({code:'',name:'',legal_name:'',email:'',phone:'',address:''});await loadOrganizations();}catch(error:any){toast.error(error?.response?.data?.message||'Gagal menambahkan company.');}finally{setSaving(false);}};
  const saveBranch=async(event:React.FormEvent)=>{event.preventDefault();setSaving(true);try{await api.post('/v1/organizations/branches',branchForm);toast.success('Branch berhasil ditambahkan beserta warehouse MAIN.');setBranchForm(current=>({...current,code:'',name:'',email:'',phone:'',address:''}));await loadOrganizations();}catch(error:any){toast.error(error?.response?.data?.message||'Gagal menambahkan branch.');}finally{setSaving(false);}};
  const startLocation=(branchId:number,location?:Location)=>{setEditingLocation(location?.id??null);setLocationForm({branch_id:String(branchId),code:location?.code??'',name:location?.name??'',type:location?.type??'store',email:'',phone:'',address:location?.address??'',latitude:location?.latitude==null?'':String(location.latitude),longitude:location?.longitude==null?'':String(location.longitude)});};
  const saveLocation=async(event:React.FormEvent)=>{event.preventDefault();if(!locationForm.branch_id)return;setSaving(true);const payload={code:locationForm.code,name:locationForm.name,type:locationForm.type,email:locationForm.email||null,phone:locationForm.phone||null,address:locationForm.address||null,latitude:locationForm.latitude===''?null:Number(locationForm.latitude),longitude:locationForm.longitude===''?null:Number(locationForm.longitude)};try{if(editingLocation){await api.put(`/v1/organizations/locations/${editingLocation}`,payload);toast.success('Location berhasil diperbarui.');}else{await api.post(`/v1/organizations/branches/${locationForm.branch_id}/locations`,payload);toast.success('Location berhasil ditambahkan.');}setEditingLocation(null);setLocationForm({branch_id:'',code:'',name:'',type:'store',email:'',phone:'',address:'',latitude:'',longitude:''});await loadOrganizations();}catch(error:any){toast.error(error?.response?.data?.message||'Gagal menyimpan location.');}finally{setSaving(false);}};
  const deactivateLocation=async(id:number)=>{if(!window.confirm('Nonaktifkan location ini?'))return;try{await api.delete(`/v1/organizations/locations/${id}`);toast.success('Location dinonaktifkan.');await loadOrganizations();}catch(error:any){toast.error(error?.response?.data?.message||'Gagal menonaktifkan location.');}};

  return <EnterpriseAdminLayout><main className="p-6 lg:p-8"><div className="mx-auto max-w-7xl space-y-6"><div><h1 className="text-2xl font-black text-stone-900">Organizations & Access</h1><p className="mt-1 text-sm text-stone-500">Kelola company, branch, location, role, dan permission pada tenant aktif.</p></div><PermissionGate permission="rbac.role.view" fallback={<p>Access denied.</p>}>{loading?<p>Loading...</p>:<>
    <section className="grid gap-6 lg:grid-cols-2">
      <form onSubmit={saveCompany} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Tambah Company</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Kode<input required value={companyForm.code} onChange={e=>setCompanyForm({...companyForm,code:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Nama<input required value={companyForm.name} onChange={e=>setCompanyForm({...companyForm,name:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Legal Name<input value={companyForm.legal_name} onChange={e=>setCompanyForm({...companyForm,legal_name:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Email<input type="email" value={companyForm.email} onChange={e=>setCompanyForm({...companyForm,email:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Telepon<input value={companyForm.phone} onChange={e=>setCompanyForm({...companyForm,phone:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Alamat<textarea value={companyForm.address} onChange={e=>setCompanyForm({...companyForm,address:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label></div><button disabled={saving} className="mt-5 rounded-xl bg-amber-700 px-5 py-2.5 font-bold text-white disabled:opacity-50">Tambah Company</button></form>
      <form onSubmit={saveBranch} className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Tambah Branch</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Company<select required value={branchForm.company_id} onChange={e=>setBranchForm({...branchForm,company_id:e.target.value})} className="mt-1 w-full rounded-xl border bg-white p-2.5 font-normal"><option value="">Pilih company</option>{companies.map(c=><option key={c.id} value={c.id}>{c.code} · {c.name}</option>)}</select></label><label className="text-sm font-bold">Kode<input required value={branchForm.code} onChange={e=>setBranchForm({...branchForm,code:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Nama<input required value={branchForm.name} onChange={e=>setBranchForm({...branchForm,name:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Tipe<input value={branchForm.type} onChange={e=>setBranchForm({...branchForm,type:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Telepon<input value={branchForm.phone} onChange={e=>setBranchForm({...branchForm,phone:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold sm:col-span-2">Alamat<textarea value={branchForm.address} onChange={e=>setBranchForm({...branchForm,address:e.target.value})} rows={2} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label></div><button disabled={saving||companies.length===0} className="mt-5 rounded-xl bg-stone-900 px-5 py-2.5 font-bold text-white disabled:opacity-50">Tambah Branch</button></form>
    </section>
    <section className="rounded-2xl border border-stone-200 bg-white p-6 shadow-sm"><h2 className="text-lg font-black">Struktur Tenant</h2><div className="mt-4 space-y-4">{companies.map(company=><div key={company.id} className="rounded-xl border p-4"><div className="font-black">🏢 {company.code} · {company.name}</div>{(company.branches||[]).map(branch=><div key={branch.id} className="mt-3 rounded-xl bg-stone-50 p-4"><div className="flex items-center justify-between"><div><div className="font-bold">📍 {branch.code} · {branch.name}</div><div className="text-xs text-stone-500">{branch.warehouses?.map(w=>`${w.code} · ${w.name}`).join(' | ')||'Warehouse belum ada'}</div></div><button onClick={()=>startLocation(branch.id)} className="rounded-lg bg-stone-900 px-3 py-2 text-xs font-bold text-white">＋ Location</button></div>{branch.locations?.length?<div className="mt-3 grid gap-2 md:grid-cols-2 lg:grid-cols-3">{branch.locations.map(location=><div key={location.id} className="rounded-xl border bg-white p-3"><div className="font-bold">{location.type==='store'?'🛒':location.type==='warehouse'?'📦':'🏛️'} {location.name}</div><div className="text-xs text-stone-400">{location.code} · {location.status}</div>{location.status==='active'&&<div className="mt-2 flex gap-2"><button onClick={()=>startLocation(branch.id,location)} className="text-xs font-bold text-blue-600">Edit</button><button onClick={()=>void deactivateLocation(location.id)} className="text-xs font-bold text-red-600">Nonaktifkan</button></div>}</div>)}</div>:<div className="mt-3 text-sm text-stone-400">Belum ada location.</div>}</div>)}</div>)}</div></section>
    {locationForm.branch_id&&<section className="rounded-2xl border border-amber-200 bg-amber-50 p-6 shadow-sm"><h2 className="text-lg font-black">{editingLocation?'Edit Location':'Tambah Location'}</h2><form onSubmit={saveLocation} className="mt-4 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><label className="text-sm font-bold">Kode<input required value={locationForm.code} onChange={e=>setLocationForm({...locationForm,code:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Nama<input required value={locationForm.name} onChange={e=>setLocationForm({...locationForm,name:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Tipe<select value={locationForm.type} onChange={e=>setLocationForm({...locationForm,type:e.target.value})} className="mt-1 w-full rounded-xl border bg-white p-2.5 font-normal"><option value="store">Store</option><option value="warehouse">Warehouse</option><option value="office">Office</option></select></label><label className="text-sm font-bold">Telepon<input value={locationForm.phone} onChange={e=>setLocationForm({...locationForm,phone:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Email<input type="email" value={locationForm.email} onChange={e=>setLocationForm({...locationForm,email:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold lg:col-span-2">Alamat<input value={locationForm.address} onChange={e=>setLocationForm({...locationForm,address:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Latitude<input type="number" step="any" value={locationForm.latitude} onChange={e=>setLocationForm({...locationForm,latitude:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><label className="text-sm font-bold">Longitude<input type="number" step="any" value={locationForm.longitude} onChange={e=>setLocationForm({...locationForm,longitude:e.target.value})} className="mt-1 w-full rounded-xl border p-2.5 font-normal" /></label><div className="lg:col-span-4 flex gap-2"><button disabled={saving} className="rounded-xl bg-amber-700 px-5 py-2.5 font-bold text-white">{editingLocation?'Simpan Perubahan':'Simpan Location'}</button><button type="button" onClick={()=>{setEditingLocation(null);setLocationForm({...locationForm,branch_id:''})}} className="rounded-xl bg-white px-5 py-2.5 font-bold">Batal</button></div></form></section>}
    <section><h2 className="text-lg font-black">Roles</h2><div className="overflow-hidden rounded-xl border bg-white"><table className="w-full text-left"><thead className="bg-stone-50"><tr><th className="p-3">Name</th><th className="p-3">Code</th><th className="p-3">Permissions</th></tr></thead><tbody>{roles.map(r=><tr key={r.id} className="border-t"><td className="p-3">{r.name}</td><td className="p-3">{r.code}</td><td className="p-3">{r.permissions?.length||0}</td></tr>)}</tbody></table></div></section><section><h2 className="text-lg font-black">Permission Catalog</h2><p className="text-sm text-stone-500">{permissions.length} permissions</p></section><section><h2 className="text-lg font-black">Recent Audit</h2><ul className="space-y-1 text-sm text-stone-600">{audits.map(a=><li key={a.id}>{a.event} · {a.module} · {a.entity_type||''} · {a.created_at}</li>)}</ul></section>
  </>}</PermissionGate></div></main></EnterpriseAdminLayout>;
}
